### PR TITLE
Use InternalCam for first person

### PR DESCRIPTION
**Pull request by JonnyOThan**
Certain graphics mods like EVE and Scatterer rely on the localspace camera for drawing effects like clouds and atmosphere when in low orbit.  The existing implementation of pulling the camera's near and far planes closer was resulting in those effects getting clipped.  See https://github.com/LGhassen/EnvironmentalVisualEnhancements/issues/24

Instead, use the InternalCamera to draw the kerbal just like in IVA mode so that we don't need to modify the local space camera's properties.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Please try to avoid committing changes to the .csproj file in the future, it causes problems

**Comment by JonnyOThan** [comment]
I made sure nothing unintentional was in there - in this case it was deleting a file that wasn't necessary anymore.  Is there a better way to do that?

**Comment by linuxgurugamer** [comment]
Just make a note if you are doing something like that, so I know what to do when it comes through.  My local .csproj file got changed by VS automatically, and I ended up with some local conflicts.  Nothing I couldn't deal with, in this case it was pretty simple to work around.  I have had people make major changes to the file which is a real PITA to deal with
Thanks for understanding

**Comment by JonnyOThan** [comment]
Understandable; it's very easy to accidentally get local-only changes in there, especially if you have to adjust configurations for your development environment.

**Pull request merged**
